{% set name = "quaternionic" %}
{% set version = "1.0.11" %}
{% set sha256 = "e8cf5ce7498bd15c02ce2fe80f62e0a18b37009097c6567c56359a49bd9960cb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip >=20.0.2
    - hatchling
  run:
    - python >=3.8
    - numpy
    - scipy
    - numba

test:
  imports:
    - quaternionic

about:
  home: https://github.com/moble/quaternionic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interpret numpy arrays as quaternionic arrays with numba acceleration
  description: |
    This package subclasses numpy's array type, interpreting the array as an
    array of quaternions, and accelerating the algebra using numba. There is
    also basic initial support for symbolic manipulation of quaternions by
    creating quaternionic arrays with sympy symbols as elements, though this
    is a work in progress.
  doc_url: https://quaternionic.readthedocs.io/
  dev_url: https://github.com/moble/quaternionic

extra:
  recipe-maintainers:
    - moble
